channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy=1.26.*
  - pandas
  #- scipy=1.9.*
  - rasterio=1.3.*
  - geopandas=0.14.*
  - openpyxl
  #- numba=0.56.*
  #- cudatoolkit
  #- colorama
  #- pyyaml
  #- xarray=2022.12.*
  #- dask
  #- numbagg
  - rioxarray
  - xlsxwriter=3.0.*
  - georasters=0.5.* #alternate backend for schu14's pixels_to_points
  - scikit-image
  - xarray=2023.5.*
  - tqdm
 
    
 